(() => {
  const sharedModules = {
    module1: {
      lines: [
        "fj fj fj fj",
        "jf jf jf jf",
        "ff jj ff jj",
        "jj ff jj ff",
        "fjf jfj fjf jfj",
        "jfj fjf jfj fjf",
        "fjj fjj fjj fjj",
        "jff jff jff jff",
        "f j f j f j f j",
        "j f j f j f j f",
        "dk dk dk dk",
        "kd kd kd kd",
        "dd kk dd kk",
        "kk dd kk dd",
        "dkd kdk dkd kdk",
        "kdk dkd kdk dkd",
        "dkk dkk dkk dkk",
        "kdd kdd kdd kdd",
        "d k d k d k d k",
        "k d k d k d k d",
        "sl sl sl sl",
        "ls ls ls ls",
        "ss ll ss ll",
        "ll ss ll ss",
        "sls lsl sls lsl",
        "lsl sls lsl sls",
        "sll sll sll sll",
        "lss lss lss lss",
        "s l s l s l s l",
        "l s l s l s l s",
        "a; a; a; a;",
        ";a ;a ;a ;a",
        "aa ;; aa ;;",
        ";; aa ;; aa",
        "a;a ;a; a;a ;a;",
        ";a; a;a ;a; a;a",
        "a;; a;; a;; a;;",
        ";aa ;aa ;aa ;aa",
        "a ; a ; a ; a ;",
        "; a ; a ; a ; a",
        "asdf jkl; asdf jkl;",
        "fdsa ;lkj fdsa ;lkj",
        "as as df df jk jk l; l;",
        "sa sa fd fd kj kj ;l ;l",
        "asd asd jkl jkl",
        "dsa dsa lkj lkj",
        "asdf asdf jkl; jkl;",
        "fjdk fjdk dkfj dkfj",
        "ajsl ajsl slaj slaj",
        "fjak ksld fjak ksld",
        "aaa sss ddd fff",
        "jjj kkk lll ;;;",
        "asdf fdsa asdf fdsa",
        "jkl; ;lkj jkl; ;lkj",
        "af af sd sd jk jk l; l;",
        "fa fa ds ds kj kj ;l ;l",
        "ad ad sf sf jl jl k; k;",
        "da da fs fs lj lj ;k ;k",
        "asdfg hjkl; asdfg hjkl;",
        "gfdsa ;lkjh gfdsa ;lkjh"
      ]
    },
    module2: {
      lines: [
        "fad dad sad lad",
        "fall sall dall jall",
        "ask flask task",
        "all as lad fad",
        "dad adds sad lads",
        "falls ask lads",
        "lass flask daff",
        "fad fad sad sad",
        "lad lad ask ask",
        "fall fall task task",
        "dash flash flask",
        "all fall last fast",
        "sad lass lass fall",
        "ask asks asked",
        "fad lads lass",
        "dark lark sark",
        "fads falls lasts",
        "daff lass flask",
        "fast fast last last",
        "sadly falsely",
        "jak jakal jask",
        "kaf kad saf laf",
        "dask lask fask",
        "jad jads jall",
        "kald fald sald",
        "fadl daskal",
        "safda lafda",
        "kadal sadal",
        "faska laska",
        "dafka salfa",
        "ads adds lads lass",
        "fad add sad lass",
        "fall all ask last",
        "salt lasts falls fast",
        "flask asks lasts",
        "sad lad asks",
        "all lads fall",
        "fall fast ask",
        "last flask sad",
        "dad asks last",
        "alfa salda falda",
        "dalsa faska",
        "sadal falds",
        "lasda kasda",
        "dafla salka",
        "laska daska",
        "sadak faldak",
        "lall sads falls",
        "flask daskal",
        "fallad laskad",
        "jkl jkl jkl",
        "asdf asdf asdf",
        "fdsa jkl; fdsa jkl;",
        "afdj slk; afdj slk;",
        "daks laks faks",
        "sald fald kald",
        "jask jals jalf",
        "kasd lask dask",
        "fadl sald lask",
        "fast lass fall"
      ]
    },
    module3: {
      lines: [
        "fast ask Fall sad",
        "add Fall ask Dad",
        "last Flask Sand",
        "all Falls fast",
        "Dad asks last",
        "sad Lad Falls",
        "Flask and Glass",
        "ask and add",
        "fast and last",
        "Sand Falls",
        "Glass Flask lasts",
        "Dad adds Sand",
        "last Fall asks",
        "sad Lads ask",
        "all Dads Fall",
        "fast Lads Dash",
        "Dash and Flash",
        "Flash asks fast",
        "Sand and Glass",
        "Flask Falls last",
        "ask Dad",
        "add Sand",
        "Fall fast",
        "last Flask",
        "sad Glass",
        "fast Dash",
        "Dad Falls",
        "ask last",
        "Sand Flask",
        "Glass Falls",
        "all Lads ask fast",
        "Dad asks and Falls",
        "Sand and Glass Fall",
        "fast Lads Dash last",
        "last Dads ask",
        "sad Lads Fall fast",
        "Dash asks fast",
        "Glass Flask and Sand",
        "Dad adds and asks",
        "last Sand Falls",
        "fast fast fast last",
        "last last ask ask",
        "Glass Flask Glass Flask",
        "Sand Sand Dad Dad",
        "Fall Fall sad sad",
        "ask ask Dash Dash",
        "Flash Flash fast fast",
        "Lads Lads Dads Dads",
        "adds adds asks asks",
        "lasts lasts Falls Falls",
        "Fall and ask",
        "last and add",
        "sad and fast",
        "Glass and Sand",
        "Dash and Flash",
        "Dad and Lad",
        "ask and Fall",
        "last and Glass",
        "Sand and last",
        "Flask and Dad",
        "fast Lads ask last",
        "Glass Falls and lasts",
        "Dad asks fast Lads",
        "Sand Falls last",
        "Dash and Flash ask",
        "sad Lads and Dads",
        "all Fall fast",
        "last Glass asks",
        "Dad adds Sand fast",
        "Flask and Glass last",
        "fast Lad",
        "last Dad",
        "sad Flask",
        "Glass Fall",
        "Sand ask",
        "Dash last",
        "Flash Fall",
        "Dad asks",
        "Lad Falls",
        "ask Glass"
      ]
    },
    module4: {
      lines: [
        "Dad asks and Falls",
        "Fall fast and ask",
        "Sand and Flask",
        "Glass Falls fast",
        "last Lads ask",
        "sad Dads add Sand",
        "fast Lads Fall last",
        "ask Dad and Fall",
        "Glass and Sand last",
        "Dad asks fast",
        "all Lads ask fast",
        "Dad asks and adds",
        "sad Lads Fall fast",
        "Glass Falls and lasts",
        "Sand and Glass Fall",
        "last Dads ask fast",
        "Flash and Dash last",
        "Dad asks for Sand",
        "all Glass Falls",
        "fast Lads ask Dad",
        "ask and add Sand",
        "Fall and ask Dad",
        "last and fast Glass",
        "Sand and Flask last",
        "Dad and Lad Fall",
        "Glass and Flask Fall",
        "sad Dads ask last",
        "fast Lads add Sand",
        "all Lads Fall fast",
        "ask Dad for Glass",
        "Dad asks last",
        "sad Lad Falls",
        "Glass Falls fast",
        "Sand lasts all Day",
        "ask fast and Fall",
        "all Lads ask Dad",
        "Flash Falls last",
        "Dad adds Sand fast",
        "Glass and Sand last",
        "ask and add fast",
        "fast Lads ask last",
        "sad Dads Fall fast",
        "Glass Flask and Sand",
        "Dad asks and adds Sand",
        "last Lads ask for Glass",
        "all Dads ask fast",
        "Sand Falls and lasts",
        "Flash and Dash Fall",
        "Glass Falls last and fast",
        "ask Dad and add Sand",
        "last Glass and Sand",
        "fast Dad and Lad",
        "sad Lads ask Dad",
        "all Flask and Glass",
        "Sand and Dash last",
        "Flash asks fast Lads",
        "Dad Falls and asks",
        "ask all sad Lads",
        "Glass lasts and Falls",
        "last Dads add Sand",
        "ask for Glass",
        "Fall and add Sand",
        "Dad asks for Flask",
        "sad Lads ask fast",
        "all Dads Fall last",
        "Glass and Sand Fall",
        "Flash asks and lasts",
        "fast Lads add Glass",
        "Dad asks and Falls fast",
        "last Flask and Glass",
        "all Lads ask last",
        "Dad asks for Sand and Glass",
        "sad Lads Fall and ask",
        "fast Dads add Sand",
        "Glass Falls and lasts fast",
        "ask Dad for Flask and Glass",
        "Sand and Glass Fall last",
        "Flash and Dash ask fast",
        "Dad asks and all Fall",
        "last Lads add Sand"
      ]
    },
    module5: {
      lines: [
        "the quick brown Fox",
        "pack my Box with five Dozen Jugs"
      ]
    }
  };

  const characterMaps = {
    de: {
      ";": "ö",
      "y": "z",
      "z": "y"
    },
    ru: {
      "q": "й",
      "w": "ц",
      "e": "у",
      "r": "к",
      "t": "е",
      "y": "н",
      "u": "г",
      "i": "ш",
      "o": "щ",
      "p": "з",
      "a": "ф",
      "s": "ы",
      "d": "в",
      "f": "а",
      "g": "п",
      "h": "р",
      "j": "о",
      "k": "л",
      "l": "д",
      ";": "ж",
      "z": "я",
      "x": "ч",
      "c": "с",
      "v": "м",
      "b": "и",
      "n": "т",
      "m": "ь",
      ",": "б",
      ".": "ю"
    }
  };

  const localizedLines = {
    de: {
      module2: [
        "das dass als all",
        "fall fass glas hall",
        "sag jag lag frag",
        "kalt klar klang glas",
        "feld fels flach flak",
        "haft halt hals halb",
        "darf fand sand land",
        "glas glas fall fall",
        "klar kalt als das",
        "schall falsch flach",
        "last fast feld glas",
        "sagt fragt jagt lag",
        "dass das als falls",
        "fall fast kalt klar",
        "glas hals halt hall",
        "falsch flach schall",
        "darf darf fand fand",
        "sand land glas fall",
        "als das falls klar",
        "kalt fast hals halt",
        "jagd lag jagt sag",
        "klar glas klang",
        "fall feld fels",
        "darf frag fragt",
        "halt hals halb",
        "dass fast falls",
        "glas klar kalt",
        "sand land fand",
        "flach falsch schall",
        "fall als das"
      ],
      module3: [
        "das Glas ist kalt",
        "der Sand liegt da",
        "fast alle fragen",
        "Karl sagt das klar",
        "falscher Fall",
        "das Feld ist flach",
        "Hans fragt Karl",
        "Glas und Sand",
        "klar und kalt",
        "falls das Glas fällt",
        "der Tag ist fast klar",
        "alle fragen Hans",
        "das Land ist flach",
        "Karl fand das Glas",
        "Hans sagt alles",
        "der Fall ist klar",
        "Sand und Glas",
        "fast alles klappt",
        "kalt klar flach",
        "das Glas ist da",
        "frag Hans",
        "sag Karl",
        "das Feld",
        "klar Fall",
        "kaltes Glas",
        "flacher Sand",
        "Hans fragt",
        "Karl sagt",
        "alles klar",
        "falls das klappt",
        "alle sagen das klar",
        "Hans fand Glas",
        "der Sand ist kalt",
        "das Land lag flach",
        "Karl fragt Hans",
        "Glas fällt fast",
        "sag das klar",
        "frag das laut",
        "Hans und Karl",
        "alles ist klar"
      ],
      module4: [
        "Hans fragt Karl und sagt alles klar",
        "das Glas fällt fast auf den Sand",
        "Karl fand das Feld am Rand",
        "alle sagen das ist klar",
        "der Sand liegt kalt im Glas",
        "Hans und Karl fragen das laut",
        "falls das klappt ist alles klar",
        "das Land ist flach und kalt",
        "Karl sagt Hans fragt das",
        "alle fanden Glas und Sand",
        "der Tag ist kalt aber klar",
        "Hans sah das Glas fallen",
        "Karl fragt nach dem Sand",
        "das Feld liegt am flachen Land",
        "alle sagen es klappt",
        "falls Karl fragt sag das klar",
        "Hans fand den Fall fast klar",
        "Glas und Sand liegen da",
        "das alles klingt klar",
        "Karl und Hans sagen das",
        "der Fall war fast klar",
        "das Glas lag im Sand",
        "alle fragen nach dem Feld",
        "Hans sagt der Sand ist kalt",
        "Karl fand Glas am Rand",
        "das Land war flach und still",
        "falls alles klappt frag Hans",
        "sag Karl alles ist klar",
        "das Glas fällt auf Sand",
        "Hans fragt und Karl sagt ja",
        "alle fanden den klaren Fall",
        "Sand und Glas lagen da",
        "das Feld war kalt",
        "Karl sagt frag Hans",
        "Hans fand alles klar",
        "der Sand war flach",
        "Glas fällt fast",
        "alle sagen klar",
        "das Land lag still",
        "Karl fragt Hans"
      ]
    },
    ru: {
      module2: [
        "да ад сад лад",
        "зал зал дал дал",
        "как клад сад",
        "даль зал лад",
        "дал дала сад лада",
        "сад лад клад",
        "зал клад лад",
        "да да сад сад",
        "лад лад как как",
        "зал зал клад клад",
        "даль жаль клад",
        "лад зал сад",
        "сад лад зал",
        "как как клад",
        "дал лад сад",
        "клад лад зал",
        "дала лад дала",
        "сад зал клад",
        "зал зал лад лад",
        "сдала сдали",
        "лад ладка клад",
        "кадка садик лад",
        "склад лад склад",
        "дал дала даль",
        "клад зал сад",
        "лад склад",
        "сад лад",
        "клад сад",
        "ладка склад",
        "да зал сад"
      ],
      module3: [
        "Сад был рядом",
        "Лад был важен",
        "как дал Влад",
        "Даль стала ясна",
        "Клад был там",
        "Сад и Клад",
        "Лад да Склад",
        "как и Лад",
        "Сад стал рядом",
        "Клад в Саду",
        "Влад дал Знак",
        "Лада ждала Дома",
        "Сад дал Покой",
        "Клад стал важен",
        "Лад был прост",
        "в Саду был Клад",
        "да ладно",
        "как стало ясно",
        "Сад и Даль",
        "Клад и Лад",
        "дай Знак",
        "ждал Влад",
        "Лад дал",
        "Сад рядом",
        "Клад дома",
        "Даль ясна",
        "Влад ждал",
        "Лада дала",
        "Сад стал",
        "Клад был",
        "Влад дал Знак",
        "Лада ждала Сад",
        "Сад был тих",
        "Клад был там",
        "как дал Лад",
        "Даль стала ясна",
        "Сад дал Свет",
        "Лад стал прост",
        "Клад в Саду",
        "да все ладно"
      ],
      module4: [
        "Влад дал Знак и ждал Ответа",
        "Лада ждала Дома и все было ладно",
        "Сад был тих и рядом был Клад",
        "как стало ясно все было просто",
        "в Саду нашли старый Клад",
        "Влад спросил и Лада дала Ответ",
        "Даль была ясна и Дорога проста",
        "Сад дал Тень и Покой",
        "Клад лежал там давно",
        "Лада сказала все ладно",
        "Влад ждал Знак у Сада",
        "как только стало ясно",
        "Сад и Дом были рядом",
        "Клад был важен для всех",
        "Лада дала Владу Знак",
        "все стало ясно к вечеру",
        "Влад нашел Клад в Саду",
        "Сад был старый и тихий",
        "Лада ждала пока Влад придет",
        "как раз все было ладно",
        "Влад дал Саду новый Вид",
        "Клад лежал возле Дома",
        "Сад стал тихим Местом",
        "Лада дала простой Ответ",
        "Влад спросил как дела",
        "все было ясно сразу",
        "Сад рядом с Домом",
        "Клад стал важной Находкой",
        "Лада ждала добрых Слов",
        "Влад дал Знак Рукой",
        "как стало ясно всем",
        "Сад был полон Света",
        "Клад нашли рядом",
        "Лада сказала ладно",
        "Влад ждал у Дома",
        "Сад дал Прохладу",
        "Даль была светла",
        "Клад был найден",
        "все стало ладно",
        "Влад и Лада ждали"
      ]
    }
  };

  const moduleNames = {
    ru: {
      module1: "Модуль 1",
      module2: "Модуль 2",
      module3: "Модуль 3",
      module4: "Модуль 4",
      module5: "Модуль 5"
    },
    de: {
      module1: "Modul 1",
      module2: "Modul 2",
      module3: "Modul 3",
      module4: "Modul 4",
      module5: "Modul 5"
    },
    en: {
      module1: "Module 1",
      module2: "Module 2",
      module3: "Module 3",
      module4: "Module 4",
      module5: "Module 5"
    }
  };

  function localizeLine(line, language) {
    const map = characterMaps[language];
    if (!map) return line;
    return [...line].map(character => map[character] || character).join("");
  }

  function buildModules(language) {
    const names = moduleNames[language] || moduleNames.en;
    const modules = {};

    Object.entries(sharedModules).forEach(([moduleId, module]) => {
      const localized = localizedLines[language]?.[moduleId];
      modules[moduleId] = {
        name: names[moduleId] || moduleId,
        lines: localized || module.lines.map(line => localizeLine(line, language))
      };
    });

    return modules;
  }

  window.PRACTICE_CONTENT = {
    ru: {
      modules: buildModules("ru")
    },
    de: {
      modules: buildModules("de")
    },
    en: {
      modules: buildModules("en")
    }
  };
})();
