const languages = {
  de: {
    name: "DE",
    keys: {
      backquote: "°\n^", digit1: "!\n1", digit2: "\"\n2", digit3: "§\n3", digit4: "$\n4", digit5: "%\n5", digit6: "&\n6", digit7: "/\n7", digit8: "(\n8", digit9: ")\n9", digit0: "=\n0", minus: "?\nß", equal: "`\n´", delete: "⌫",
      tab: "tab", q: "Q", w: "W", e: "E", r: "R", t: "T", y: "Z", u: "U", i: "I", o: "O", p: "P", bracketLeft: "Ü", bracketRight: "*\n+", backslash: "'\n#",
      caps: "caps lock", a: "A", s: "S", d: "D", f: "F", g: "G", h: "H", j: "J", k: "K", l: "L", semicolon: "Ö", quote: "Ä", enter: "↵",
      shiftLeft: "shift", isoIntl: ">\n<", z: "Y", x: "X", c: "C", v: "V", b: "B", n: "N", m: "M", comma: ";\n,", period: ":\n.", slash: "_\n-", shiftRight: "shift",
      fn: "fn", control: "control", optionLeft: "option", commandLeft: "command", space: "", commandRight: "command", optionRight: "option", arrowLeft: "◂", arrowUp: "▴", arrowDown: "▾", arrowRight: "▸"
    }
  },
  en: {
    name: "EN",
    keys: {
      backquote: "~\n`", digit1: "!\n1", digit2: "@\n2", digit3: "#\n3", digit4: "$\n4", digit5: "%\n5", digit6: "^\n6", digit7: "&\n7", digit8: "*\n8", digit9: "(\n9", digit0: ")\n0", minus: "_\n-", equal: "+\n=", delete: "⌫",
      tab: "tab", q: "Q", w: "W", e: "E", r: "R", t: "T", y: "Y", u: "U", i: "I", o: "O", p: "P", bracketLeft: "[", bracketRight: "]", backslash: "\\",
      caps: "caps lock", a: "A", s: "S", d: "D", f: "F", g: "G", h: "H", j: "J", k: "K", l: "L", semicolon: ":\n;", quote: "\"\n'", enter: "↵",
      shiftLeft: "shift", isoIntl: ">\n<", z: "Z", x: "X", c: "C", v: "V", b: "B", n: "N", m: "M", comma: ",", period: ".", slash: "?\n/", shiftRight: "shift",
      fn: "fn", control: "control", optionLeft: "option", commandLeft: "command", space: "", commandRight: "command", optionRight: "option", arrowLeft: "◂", arrowUp: "▴", arrowDown: "▾", arrowRight: "▸"
    }
  },
  ru: {
    name: "RU",
    keys: {
      backquote: "Ё", digit1: "!\n1", digit2: "\"\n2", digit3: "№\n3", digit4: ";\n4", digit5: "%\n5", digit6: ":\n6", digit7: "?\n7", digit8: "*\n8", digit9: "(\n9", digit0: ")\n0", minus: "_\n-", equal: "+\n=", delete: "⌫",
      tab: "tab", q: "Й", w: "Ц", e: "У", r: "К", t: "Е", y: "Н", u: "Г", i: "Ш", o: "Щ", p: "З", bracketLeft: "Х", bracketRight: "Ъ", backslash: "\\",
      caps: "caps lock", a: "Ф", s: "Ы", d: "В", f: "А", g: "П", h: "Р", j: "О", k: "Л", l: "Д", semicolon: "Ж", quote: "Э", enter: "↵",
      shiftLeft: "shift", isoIntl: ">\n<", z: "Я", x: "Ч", c: "С", v: "М", b: "И", n: "Т", m: "Ь", comma: "Б", period: "Ю", slash: ",\n.", shiftRight: "shift",
      fn: "fn", control: "control", optionLeft: "option", commandLeft: "command", space: "", commandRight: "command", optionRight: "option", arrowLeft: "◂", arrowUp: "▴", arrowDown: "▾", arrowRight: "▸"
    }
  },
  uk: {
    name: "UA",
    keys: {
      backquote: "'", digit1: "!\n1", digit2: "\"\n2", digit3: "№\n3", digit4: ";\n4", digit5: "%\n5", digit6: ":\n6", digit7: "?\n7", digit8: "*\n8", digit9: "(\n9", digit0: ")\n0", minus: "_\n-", equal: "+\n=", delete: "⌫",
      tab: "tab", q: "Й", w: "Ц", e: "У", r: "К", t: "Е", y: "Н", u: "Г", i: "Ш", o: "Щ", p: "З", bracketLeft: "Х", bracketRight: "Ї", backslash: "\\",
      caps: "caps lock", a: "Ф", s: "І", d: "В", f: "А", g: "П", h: "Р", j: "О", k: "Л", l: "Д", semicolon: "Ж", quote: "Є", enter: "↵",
      shiftLeft: "shift", isoIntl: ">\n<", z: "Я", x: "Ч", c: "С", v: "М", b: "И", n: "Т", m: "Ь", comma: "Б", period: "Ю", slash: ",\n.", shiftRight: "shift",
      fn: "fn", control: "control", optionLeft: "option", commandLeft: "command", space: "", commandRight: "command", optionRight: "option", arrowLeft: "◂", arrowUp: "▴", arrowDown: "▾", arrowRight: "▸"
    }
  },
  kk: {
    name: "KZ",
    keys: {
      backquote: ")\n(", digit1: "!\n\"", digit2: "Ә\nә", digit3: "І\nі", digit4: "Ң\nң", digit5: "Ғ\nғ", digit6: ";\n,", digit7: ":\n.", digit8: "Ү\nү", digit9: "Ұ\nұ", digit0: "Қ\nқ", minus: "Ө\nө", equal: "Һ\nһ", delete: "⌫",
      tab: "tab", q: "Й", w: "Ц", e: "У", r: "К", t: "Е", y: "Н", u: "Г", i: "Ш", o: "Щ", p: "З", bracketLeft: "Х", bracketRight: "Ъ", backslash: "/\n\\",
      caps: "caps lock", a: "Ф", s: "Ы", d: "В", f: "А", g: "П", h: "Р", j: "О", k: "Л", l: "Д", semicolon: "Ж", quote: "Э", enter: "↵",
      shiftLeft: "shift", isoIntl: "|\n\\", z: "Я", x: "Ч", c: "С", v: "М", b: "И", n: "Т", m: "Ь", comma: "Б", period: "Ю", slash: "?\n№", shiftRight: "shift",
      fn: "fn", control: "control", optionLeft: "option", commandLeft: "command", space: "", commandRight: "command", optionRight: "option", arrowLeft: "◂", arrowUp: "▴", arrowDown: "▾", arrowRight: "▸"
    }
  }
};

const geometry = [
  ["backquote", 1, 3, 16, "stacked"], ["digit1", 1, 21, 16, "stacked"], ["digit2", 1, 39, 16, "stacked"], ["digit3", 1, 57, 16, "stacked"], ["digit4", 1, 75, 16, "stacked"], ["digit5", 1, 93, 16, "stacked"], ["digit6", 1, 111, 16, "stacked"], ["digit7", 1, 129, 16, "stacked"], ["digit8", 1, 147, 16, "stacked"], ["digit9", 1, 165, 16, "stacked"], ["digit0", 1, 183, 16, "stacked"], ["minus", 1, 201, 16, "stacked"], ["equal", 1, 219, 16, "stacked"], ["delete", 1, 237, 24, "function align-right"],
  ["tab", 2, 3, 25, "function align-left"], ["q", 2, 30, 16], ["w", 2, 48, 16], ["e", 2, 66, 16], ["r", 2, 84, 16], ["t", 2, 102, 16], ["y", 2, 120, 16], ["u", 2, 138, 16], ["i", 2, 156, 16], ["o", 2, 174, 16], ["p", 2, 192, 16], ["bracketLeft", 2, 210, 16], ["bracketRight", 2, 228, 16, "stacked"],
  ["caps", 3, 3, 29, "function align-left"], ["a", 3, 34, 16], ["s", 3, 52, 16], ["d", 3, 70, 16], ["f", 3, 88, 16, "home"], ["g", 3, 106, 16], ["h", 3, 124, 16], ["j", 3, 142, 16, "home"], ["k", 3, 160, 16], ["l", 3, 178, 16], ["semicolon", 3, 196, 16], ["quote", 3, 214, 16], ["backslash", 3, 232, 16, "stacked"], ["enter", 2, 246, 15, "function key-enter", 2],
  ["shiftLeft", 4, 3, 20, "function align-left"], ["isoIntl", 4, 25, 16, "iso"], ["z", 4, 43, 16], ["x", 4, 61, 16], ["c", 4, 79, 16], ["v", 4, 97, 16], ["b", 4, 115, 16], ["n", 4, 133, 16], ["m", 4, 151, 16], ["comma", 4, 169, 16, "stacked"], ["period", 4, 187, 16, "stacked"], ["slash", 4, 205, 16, "stacked"], ["shiftRight", 4, 223, 38, "function align-right"],
  ["fn", 5, 3, 16, "function align-left"], ["control", 5, 21, 16, "function"], ["optionLeft", 5, 39, 16, "function"], ["commandLeft", 5, 57, 20, "function"], ["space", 5, 79, 88], ["commandRight", 5, 169, 20, "function"], ["optionRight", 5, 191, 16, "function"], ["arrowLeft", 5, 209, 16, "function"], ["arrowUp", 5, 227, 16, "function"], ["arrowDown", 5, 227, 16, "function"], ["arrowRight", 5, 245, 16, "function"]
];

const fingerIds = [
  "left-pinky",
  "left-ring",
  "left-middle",
  "left-index",
  "left-thumb",
  "right-thumb",
  "right-index",
  "right-middle",
  "right-ring",
  "right-pinky"
];

const defaultFingerMap = {
  "left-pinky": ["backquote", "digit1", "tab", "q", "caps", "a", "shiftLeft", "isoIntl", "z", "fn", "control"],
  "left-ring": ["digit2", "w", "s", "x"],
  "left-middle": ["digit3", "e", "d", "c"],
  "left-index": ["digit4", "digit5", "r", "t", "f", "g", "v", "b"],
  "left-thumb": ["space", "optionLeft", "commandLeft"],
  "right-thumb": ["space", "commandRight", "optionRight"],
  "right-index": ["digit6", "digit7", "y", "u", "h", "j", "n", "m"],
  "right-middle": ["digit8", "i", "k", "comma"],
  "right-ring": ["digit9", "o", "l", "period"],
  "right-pinky": ["digit0", "minus", "equal", "delete", "p", "bracketLeft", "bracketRight", "backslash", "enter", "semicolon", "quote", "slash", "shiftRight", "arrowLeft", "arrowUp", "arrowDown", "arrowRight"]
};

const fixedHandCalibrationPx = {
  "right-pinky": { x: 167.94351, y: 92.733147 },
  "right-ring": { x: -54.951939, y: 43.804206 },
  "right-middle": { x: -235.750203, y: 50.371119 },
  "right-index": { x: -413.310681, y: 97.829883 },
  "right-thumb": { x: -551.150217, y: 369.546408 }
};

const uiText = {
  de: {
    settings: "Einstellungen",
    generalSettings: "Allgemein",
    displaySettings: "Anzeige",
    language: "Sprache",
    keyboardLanguage: "Tastatursprache",
    module: "Modul",
    sound: "Klang",
    practiceTextSize: "Textgröße",
    theme: "Thema",
    lightTheme: "Hell",
    darkTheme: "Dunkel",
    keySoundOn: "Tastentöne ein",
    keySoundOff: "Tastentöne aus",
    toggleOn: "Ein",
    toggleOff: "Aus",
    learningProgram: "Lernprogramm",
    statistics: "Statistik",
    help: "Hilfe",
    allModules: "Alle Module",
    currentModuleProgress: "Fortschritt des aktuellen Moduls",
    resetCurrentModuleProgress: "Fortschritt des aktuellen Moduls zurücksetzen",
    lessonTarget: "Ziele",
    gradeRepeat: "wiederholen",
    gradeWeak: "schwach",
    gradeOk: "ok",
    gradeExcellent: "sehr gut",
    assistants: "Assistenten",
    keyHighlight: "Tasten hervorheben",
    fingerZones: "Fingerzonen",
    fingerHighlight: "Finger hervorheben",
    pressHighlight: "Tastendrücke hervorheben",
    showFingers: "Finger anzeigen",
    alternateLines: "Jede zweite Zeile",
    metronome: "Metronom",
    textPractice: "Textübung",
    practiceText: "Text",
    randomText: "Zufallstext",
    customText: "Eigener Text",
    refreshText: "Text neu laden",
    startPractice: "Start",
    textSourceLoading: "Text wird geladen...",
    textSourceReady: "Text ist bereit.",
    textSourceFallback: "Quelle nicht erreichbar. Lokaler Text wird verwendet.",
    textTooShort: "Füge mehr Text ein.",
    practiceErrors: "Fehler",
    trainingTime: "Trainingszeit",
    dailyStats: "Tageswerte",
    today: "Heute",
    helpPractice: "Tippe die Zeile auf dem Bildschirm. Drücke nach der fertigen Zeile Enter, um weiterzugehen.",
    helpProgram: "Im Lernprogramm kannst du ein Modul wählen und den Fortschritt des aktuellen Moduls zurücksetzen.",
    helpFingering: "In der Applikatur-Einstellung wählst du einen Finger und weist Tasten direkt auf der Tastatur zu.",
    fingerMap: "Fingerkarte",
    openFingerMap: "Fingerkarte öffnen",
    finger: "Finger",
    emptyFinger: "Noch keine Tasten",
    keyCount: "Tasten",
    fingerEditorModeTitle: "Applikatur bearbeiten",
    currentFinger: "Ausgewählt: {finger}",
    practiceAccuracy: "Genauigkeit",
    practiceSpeed: "Tempo",
    practiceSpeedUnit: "Anschl./min",
    targetLines: "Zeilen",
    moduleLines: "Zeilen",
    resetModuleProgress: "Modulfortschritt zurücksetzen",
    moduleProgressReset: "Modulfortschritt zurückgesetzt.",
    save: "Speichern",
    cancel: "Abbrechen",
    restoreDefaults: "Standardeinstellungen wiederherstellen",
    settingsSaved: "Einstellungen gespeichert.",
    fingerMapSaved: "Fingerkarte gespeichert.",
    draftKeyAssigned: "\"{key}\" ist jetzt bei {finger}. Zum Übernehmen unten speichern.",
    resetSettings: "Einstellungen zurücksetzen",
    settingsReset: "Fingerkarte zurückgesetzt.",
    showFingeringTour: "Kurz zeigen",
    tourNext: "Weiter",
    tourDone: "Schließen",
    tourSkip: "Überspringen",
    tourSettingsStep: "Wenn sich eine Taste unbequem anfühlt, öffnest du hier die Fingerkarte.",
    tourFingerMapStep: "Hier wählst du den passenden Finger. FlyKey zeigt gleich automatisch, wie die Finger wechseln und welche Tasten dazugehören.",
    tourKeyboardStep: "Wenn du fertig bist, drück unten auf Speichern oder Abbrechen und mach mit der Übung weiter.",
    lesson4FingeringReminder: "Jetzt kommen unbequemere Tasten dazu. Wenn sich etwas nach Strecken anfühlt, kannst du die Fingerkarte noch einmal prüfen.",
    openFingerMapAction: "Fingerkarte öffnen",
    close: "Schließen",
    fingerNames: {
      "left-pinky": "Linker kleiner Finger",
      "left-ring": "Linker Ringfinger",
      "left-middle": "Linker Mittelfinger",
      "left-index": "Linker Zeigefinger",
      "left-thumb": "Linker Daumen",
      "right-thumb": "Rechter Daumen",
      "right-index": "Rechter Zeigefinger",
      "right-middle": "Rechter Mittelfinger",
      "right-ring": "Rechter Ringfinger",
      "right-pinky": "Rechter kleiner Finger"
    }
  },
  en: {
    settings: "Settings",
    generalSettings: "General",
    displaySettings: "Display",
    language: "Language",
    keyboardLanguage: "Keyboard language",
    module: "Module",
    sound: "Sound",
    practiceTextSize: "Text size",
    theme: "Theme",
    lightTheme: "Light",
    darkTheme: "Dark",
    keySoundOn: "Key sound on",
    keySoundOff: "Key sound off",
    toggleOn: "On",
    toggleOff: "Off",
    learningProgram: "Learning Program",
    statistics: "Statistics",
    help: "Help",
    allModules: "All modules",
    currentModuleProgress: "Current module progress",
    resetCurrentModuleProgress: "Reset current module progress",
    lessonTarget: "Goals",
    gradeRepeat: "repeat",
    gradeWeak: "weak",
    gradeOk: "ok",
    gradeExcellent: "excellent",
    assistants: "Assistants",
    keyHighlight: "Key highlight",
    fingerZones: "Finger zones",
    fingerHighlight: "Finger highlight",
    pressHighlight: "Press highlight",
    showFingers: "Show fingers",
    alternateLines: "Every other line",
    metronome: "Metronome",
    textPractice: "Text Practice",
    practiceText: "Text",
    randomText: "Random Text",
    customText: "Custom Text",
    refreshText: "Refresh Text",
    startPractice: "Start",
    textSourceLoading: "Loading text...",
    textSourceReady: "Text is ready.",
    textSourceFallback: "Source unavailable. Using local text.",
    textTooShort: "Add more text.",
    practiceErrors: "Errors",
    trainingTime: "Training time",
    dailyStats: "Daily stats",
    today: "Today",
    helpPractice: "Type the line on screen. When the line is complete, press Enter to continue.",
    helpProgram: "In the learning program, you can choose a module and reset the current module progress.",
    helpFingering: "In fingering setup, choose a finger and assign keys directly on the keyboard.",
    fingerMap: "Finger Map",
    openFingerMap: "Open Finger Map",
    finger: "Finger",
    emptyFinger: "No keys yet",
    keyCount: "keys",
    fingerEditorModeTitle: "Fingering Mapping Mode",
    currentFinger: "Selected: {finger}",
    practiceAccuracy: "Accuracy",
    practiceSpeed: "Speed",
    practiceSpeedUnit: "cpm",
    targetLines: "Lines",
    moduleLines: "lines",
    resetModuleProgress: "Reset module progress",
    moduleProgressReset: "Module progress reset.",
    save: "Save",
    cancel: "Cancel",
    restoreDefaults: "Restore Defaults",
    settingsSaved: "Settings saved.",
    fingerMapSaved: "Finger map saved.",
    draftKeyAssigned: "\"{key}\" is now assigned to {finger}. Save below to apply it.",
    resetSettings: "Reset Settings",
    settingsReset: "Finger map reset.",
    showFingeringTour: "Show me",
    tourNext: "Next",
    tourDone: "Close",
    tourSkip: "Skip",
    tourSettingsStep: "If a key feels uncomfortable, this is where you open the finger map.",
    tourFingerMapStep: "This is where you choose the finger you need. FlyKey will quickly show how the fingers switch and which keys belong to each one.",
    tourKeyboardStep: "When you are done, press Save or Cancel below and continue the lesson.",
    lesson4FingeringReminder: "Now the keys get less comfortable. If something feels like a stretch, remember that you can check the finger map again.",
    openFingerMapAction: "Open Finger Map",
    close: "Close",
    fingerNames: {
      "left-pinky": "Left Pinky",
      "left-ring": "Left Ring",
      "left-middle": "Left Middle",
      "left-index": "Left Index",
      "left-thumb": "Left Thumb",
      "right-thumb": "Right Thumb",
      "right-index": "Right Index",
      "right-middle": "Right Middle",
      "right-ring": "Right Ring",
      "right-pinky": "Right Pinky"
    }
  },
  ru: {
    settings: "Настройки",
    generalSettings: "Основные",
    displaySettings: "Отображение",
    language: "Язык",
    keyboardLanguage: "Язык клавиатуры",
    module: "Модуль",
    sound: "Звук",
    practiceTextSize: "Размер текста",
    theme: "Тема",
    lightTheme: "Светлая",
    darkTheme: "Тёмная",
    keySoundOn: "Звук клавиш включён",
    keySoundOff: "Звук клавиш выключен",
    toggleOn: "Вкл",
    toggleOff: "Выкл",
    learningProgram: "Программа обучения",
    statistics: "Статистика",
    help: "Помощь",
    allModules: "Все модули",
    currentModuleProgress: "Прогресс текущего модуля",
    resetCurrentModuleProgress: "Сбросить прогресс текущего модуля",
    lessonTarget: "Цели",
    gradeRepeat: "повтор",
    gradeWeak: "слабый результат",
    gradeOk: "нормально",
    gradeExcellent: "отлично",
    assistants: "Ассистенты",
    keyHighlight: "Подсветка клавиш",
    fingerZones: "Зоны пальцев",
    fingerHighlight: "Подсветка пальцев",
    pressHighlight: "Подсветка нажатий",
    showFingers: "Показывать пальцы",
    alternateLines: "Режим \"через строку\"",
    metronome: "Метроном",
    textPractice: "Текстовая практика",
    practiceText: "Текст",
    randomText: "Случайный текст",
    customText: "Пользовательский текст",
    refreshText: "Обновить текст",
    startPractice: "Пуск",
    textSourceLoading: "Загружаю текст...",
    textSourceReady: "Текст готов.",
    textSourceFallback: "Источник недоступен. Использую локальный текст.",
    textTooShort: "Добавь больше текста.",
    practiceErrors: "Ошибки",
    trainingTime: "Время тренировки",
    dailyStats: "Показатели по дням",
    today: "Сегодня",
    helpPractice: "Печатай строку на экране. После завершения строки нажми Enter, чтобы перейти дальше.",
    helpProgram: "В программе обучения можно выбрать модуль и сбросить прогресс текущего модуля.",
    helpFingering: "В настройке аппликатуры выбери палец и назначай клавиши прямо на клавиатуре.",
    fingerMap: "Карта пальцев",
    openFingerMap: "Настройка аппликатуры",
    finger: "Палец",
    emptyFinger: "Пока нет клавиш",
    keyCount: "клавиш",
    fingerEditorModeTitle: "Режим настройки аппликатуры",
    currentFinger: "Выбран палец: {finger}",
    practiceAccuracy: "Точность",
    practiceSpeed: "Скорость",
    practiceSpeedUnit: "зн/мин",
    targetLines: "Строки",
    moduleLines: "строк",
    resetModuleProgress: "Сбросить прогресс модуля",
    moduleProgressReset: "Прогресс модуля сброшен.",
    save: "Сохранить",
    cancel: "Отменить",
    restoreDefaults: "Вернуть настройки по умолчанию",
    settingsSaved: "Настройки сохранены.",
    fingerMapSaved: "Карта пальцев сохранена.",
    draftKeyAssigned: "Клавиша \"{key}\" теперь у пальца \"{finger}\". Для применения нажми Сохранить.",
    resetSettings: "Сбросить настройки",
    settingsReset: "Карта пальцев сброшена.",
    showFingeringTour: "Показать настройку",
    tourNext: "Далее",
    tourDone: "Закрыть",
    tourSkip: "Пропустить",
    tourSettingsStep: "Если какая-то клавиша ощущается неудобно, карту пальцев можно открыть здесь.",
    tourFingerMapStep: "Здесь ты можешь выбрать палец, которым хочешь нажимать нужные клавиши.",
    tourKeyboardStep: "После настройки аппликатуры нажми «Сохранить» и продолжай упражнения.\nЕсли ничего менять не нужно — просто нажми «Отмена».",
    lesson4FingeringReminder: "Теперь появились менее удобные клавиши. Если где-то приходится тянуться, помни: карту пальцев можно проверить ещё раз.",
    openFingerMapAction: "Открыть карту",
    close: "Закрыть",
    fingerNames: {
      "left-pinky": "Левый мизинец",
      "left-ring": "Левый безымянный",
      "left-middle": "Левый средний",
      "left-index": "Левый указательный",
      "left-thumb": "Левый большой палец",
      "right-thumb": "Правый большой палец",
      "right-index": "Правый указательный",
      "right-middle": "Правый средний",
      "right-ring": "Правый безымянный",
      "right-pinky": "Правый мизинец"
    }
  },
  uk: {
    settings: "Налаштування",
    generalSettings: "Основне",
    displaySettings: "Відображення",
    language: "Мова",
    keyboardLanguage: "Мова клавіатури",
    module: "Модуль",
    sound: "Звук",
    practiceTextSize: "Розмір тексту",
    theme: "Тема",
    lightTheme: "Світла",
    darkTheme: "Темна",
    keySoundOn: "Звук клавіш увімкнено",
    keySoundOff: "Звук клавіш вимкнено",
    toggleOn: "Увімк.",
    toggleOff: "Вимк.",
    learningProgram: "Програма навчання",
    statistics: "Статистика",
    help: "Довідка",
    allModules: "Усі модулі",
    currentModuleProgress: "Прогрес поточного модуля",
    resetCurrentModuleProgress: "Скинути прогрес поточного модуля",
    lessonTarget: "Цілі",
    gradeRepeat: "повторити",
    gradeWeak: "поки слабко",
    gradeOk: "добре",
    gradeExcellent: "відмінно",
    assistants: "Підказки",
    keyHighlight: "Підсвічування клавіш",
    fingerZones: "Зони пальців",
    fingerHighlight: "Підсвічування пальців",
    pressHighlight: "Підсвічування натискань",
    showFingers: "Показувати пальці",
    alternateLines: "Режим через рядок",
    metronome: "Метроном",
    textPractice: "Текстова практика",
    practiceText: "Текст",
    randomText: "Випадковий текст",
    customText: "Власний текст",
    refreshText: "Оновити текст",
    startPractice: "Старт",
    textSourceLoading: "Завантажую текст...",
    textSourceReady: "Текст готовий.",
    textSourceFallback: "Джерело недоступне. Використовую локальний текст.",
    textTooShort: "Додайте більше тексту.",
    practiceErrors: "Помилки",
    trainingTime: "Час тренування",
    dailyStats: "Показники за днями",
    today: "Сьогодні",
    helpPractice: "Набирай рядок на екрані. Коли рядок завершено, натисни Enter, щоб перейти далі.",
    helpProgram: "У програмі навчання можна вибрати модуль і скинути прогрес поточного модуля.",
    helpFingering: "У налаштуванні аплікатури вибери палець і призначай клавіші прямо на клавіатурі.",
    fingerMap: "Карта пальців",
    openFingerMap: "Налаштування аплікатури",
    finger: "Палець",
    emptyFinger: "Клавіш ще немає",
    keyCount: "клавіш",
    fingerEditorModeTitle: "Редагування аплікатури",
    currentFinger: "Вибрано: {finger}",
    practiceAccuracy: "Точність",
    practiceSpeed: "Швидкість",
    practiceSpeedUnit: "зн/хв",
    targetLines: "Рядки",
    moduleLines: "рядків",
    resetModuleProgress: "Скинути прогрес модуля",
    moduleProgressReset: "Прогрес модуля скинуто.",
    save: "Зберегти",
    cancel: "Скасувати",
    restoreDefaults: "Повернути типові налаштування",
    settingsSaved: "Налаштування збережено.",
    fingerMapSaved: "Карту пальців збережено.",
    draftKeyAssigned: "Клавішу \"{key}\" тепер призначено пальцю \"{finger}\". Щоб застосувати зміни, натисни Зберегти.",
    resetSettings: "Скинути налаштування",
    settingsReset: "Карту пальців скинуто.",
    showFingeringTour: "Показати налаштування",
    tourNext: "Далі",
    tourDone: "Закрити",
    tourSkip: "Пропустити",
    tourSettingsStep: "Якщо якась клавіша відчувається незручно, карту пальців можна відкрити тут.",
    tourFingerMapStep: "Тут вибирається потрібний палець. FlyKey зараз сам покаже, як пальці перемикаються і які клавіші до них належать.",
    tourKeyboardStep: "Коли завершиш, натисни внизу Зберегти або Скасувати й продовжуй вправу.",
    lesson4FingeringReminder: "Тепер з'явилися менш зручні клавіші. Якщо десь доводиться тягнутися, пам'ятай: карту пальців можна перевірити ще раз.",
    openFingerMapAction: "Відкрити карту",
    close: "Закрити",
    fingerNames: {
      "left-pinky": "Лівий мізинець",
      "left-ring": "Лівий безіменний",
      "left-middle": "Лівий середній",
      "left-index": "Лівий вказівний",
      "left-thumb": "Лівий великий палець",
      "right-thumb": "Правий великий палець",
      "right-index": "Правий вказівний",
      "right-middle": "Правий середній",
      "right-ring": "Правий безіменний",
      "right-pinky": "Правий мізинець"
    }
  },
  kk: {
    settings: "Баптаулар",
    generalSettings: "Негізгі",
    displaySettings: "Көрсету",
    language: "Тіл",
    keyboardLanguage: "Пернетақта тілі",
    module: "Модуль",
    sound: "Дыбыс",
    practiceTextSize: "Мәтін өлшемі",
    theme: "Тақырып",
    lightTheme: "Жарық",
    darkTheme: "Қараңғы",
    keySoundOn: "Перне дыбысы қосулы",
    keySoundOff: "Перне дыбысы өшірулі",
    toggleOn: "Қос.",
    toggleOff: "Өш.",
    learningProgram: "Оқу бағдарламасы",
    statistics: "Статистика",
    help: "Көмек",
    allModules: "Барлық модульдер",
    currentModuleProgress: "Ағымдағы модуль прогресі",
    resetCurrentModuleProgress: "Ағымдағы модуль прогресін өшіру",
    lessonTarget: "Мақсаттар",
    gradeRepeat: "қайталау",
    gradeWeak: "әлсіздеу",
    gradeOk: "жақсы",
    gradeExcellent: "өте жақсы",
    assistants: "Көмекшілер",
    keyHighlight: "Пернелерді ерекшелеу",
    fingerZones: "Саусақ аймақтары",
    fingerHighlight: "Саусақтарды ерекшелеу",
    pressHighlight: "Басуларды ерекшелеу",
    showFingers: "Саусақтарды көрсету",
    alternateLines: "Бір жолдан кейін режимі",
    metronome: "Метроном",
    textPractice: "Мәтінмен жаттығу",
    practiceText: "Мәтін",
    randomText: "Кездейсоқ мәтін",
    customText: "Өз мәтініңіз",
    refreshText: "Мәтінді жаңарту",
    startPractice: "Старт",
    textSourceLoading: "Мәтін жүктеліп жатыр...",
    textSourceReady: "Мәтін дайын.",
    textSourceFallback: "Дереккөз қолжетімсіз. Жергілікті мәтін қолданылады.",
    textTooShort: "Көбірек мәтін қосыңыз.",
    practiceErrors: "Қателер",
    trainingTime: "Жаттығу уақыты",
    dailyStats: "Күндер бойынша көрсеткіштер",
    today: "Бүгін",
    helpPractice: "Экрандағы жолды теріңіз. Жол аяқталған соң келесіге өту үшін Enter басыңыз.",
    helpProgram: "Оқу бағдарламасында модуль таңдауға және ағымдағы модуль прогресін өшіруге болады.",
    helpFingering: "Аппликатура баптауында саусақты таңдап, пернелерді пернетақтадан тікелей тағайындаңыз.",
    fingerMap: "Саусақ картасы",
    openFingerMap: "Аппликатураны баптау",
    finger: "Саусақ",
    emptyFinger: "Әзірге перне жоқ",
    keyCount: "перне",
    fingerEditorModeTitle: "Аппликатураны өңдеу",
    currentFinger: "Таңдалды: {finger}",
    practiceAccuracy: "Дәлдік",
    practiceSpeed: "Жылдамдық",
    practiceSpeedUnit: "таң/мин",
    targetLines: "Жолдар",
    moduleLines: "жол",
    resetModuleProgress: "Модуль прогресін өшіру",
    moduleProgressReset: "Модуль прогресі өшірілді.",
    save: "Сақтау",
    cancel: "Болдырмау",
    restoreDefaults: "Әдепкі баптауларды қайтару",
    settingsSaved: "Баптаулар сақталды.",
    fingerMapSaved: "Саусақ картасы сақталды.",
    draftKeyAssigned: "\"{key}\" пернесі енді \"{finger}\" саусағына тағайындалды. Қолдану үшін Сақтау басыңыз.",
    resetSettings: "Баптауларды өшіру",
    settingsReset: "Саусақ картасы өшірілді.",
    showFingeringTour: "Баптауды көрсету",
    tourNext: "Әрі қарай",
    tourDone: "Жабу",
    tourSkip: "Өткізіп жіберу",
    tourSettingsStep: "Егер бір перне ыңғайсыз сезілсе, саусақ картасын осы жерден ашуға болады.",
    tourFingerMapStep: "Қажет саусақ осы жерде таңдалады. FlyKey қазір саусақтардың қалай ауысатынын және қай пернелер тиесілі екенін өзі көрсетеді.",
    tourKeyboardStep: "Аяқтаған соң төмендегі Сақтау немесе Болдырмау батырмасын басып, жаттығуды жалғастырыңыз.",
    lesson4FingeringReminder: "Енді ыңғайсыздау пернелер пайда болды. Бір жерге созылу керек болса, саусақ картасын қайта қарап шығуға болады.",
    openFingerMapAction: "Картаны ашу",
    close: "Жабу",
    fingerNames: {
      "left-pinky": "Сол жақ шынашақ",
      "left-ring": "Сол жақ аты жоқ саусақ",
      "left-middle": "Сол жақ ортаңғы саусақ",
      "left-index": "Сол жақ сұқ саусақ",
      "left-thumb": "Сол жақ бас бармақ",
      "right-thumb": "Оң жақ бас бармақ",
      "right-index": "Оң жақ сұқ саусақ",
      "right-middle": "Оң жақ ортаңғы саусақ",
      "right-ring": "Оң жақ аты жоқ саусақ",
      "right-pinky": "Оң жақ шынашақ"
    }
  }
};
