const keyboard = document.querySelector("#keyboard");
const keyboardScale = document.querySelector("#keyboardScale");
const keyboardWrap = document.querySelector("#keyboardWrap");
const handsLayer = document.querySelector("#handsLayer");
const leftHand = document.querySelector(".hand.left");
const rightHand = document.querySelector(".hand.right");
let leftFingerNodes = Array.from(document.querySelectorAll('.hand.left .finger[data-finger]'));
let rightFingerNodes = Array.from(document.querySelectorAll('.hand.right .finger[data-finger]'));
const settingsToggle = document.querySelector("#settingsToggle");
const pageTitle = document.querySelector("#pageTitle");
const onboardingDialog = document.querySelector("#onboardingDialog");
const onboardingText = document.querySelector("#onboardingText");
const onboardingNext = document.querySelector("#onboardingNext");
const onboardingCharacter = document.querySelector("#onboardingCharacter");
const lessonTipDialog = document.querySelector("#lessonTipDialog");
const lessonStartTitle = document.querySelector("#lessonStartTitle");
const lessonStartPurpose = document.querySelector("#lessonStartPurpose");
const lessonTipText = document.querySelector("#lessonTipText");
const lessonTipStart = document.querySelector("#lessonTipStart");
const lessonTipExtra = document.querySelector("#lessonTipExtra");
const lessonTipCharacter = document.querySelector("#lessonTipCharacter");
const completionDialog = document.querySelector("#completionDialog");
const completionStars = document.querySelector("#completionStars");
const completionText = document.querySelector("#completionText");
const completionNext = document.querySelector("#completionNext");
const completionExtra = document.querySelector("#completionExtra");
const completionCharacter = document.querySelector("#completionCharacter");
const nextModuleDialog = document.querySelector("#nextModuleDialog");
const nextModuleTitle = document.querySelector("#nextModuleTitle");
const nextModulePurpose = document.querySelector("#nextModulePurpose");
const nextModuleNext = document.querySelector("#nextModuleNext");
const nextModuleCharacter = document.querySelector("#nextModuleCharacter");
const settingsDialog = document.querySelector("#settingsDialog");
const settingsTitle = document.querySelector("#settingsTitle");
const settingsClose = document.querySelector("#settingsClose");
const languageLabel = document.querySelector("#languageLabel");
const moduleLabel = document.querySelector("#moduleLabel");
const soundLabel = document.querySelector("#soundLabel");
const keySoundToggle = document.querySelector("#keySoundToggle");
const keySoundIcon = document.querySelector("#keySoundIcon");
const keySoundToggleText = document.querySelector("#keySoundToggleText");
const practiceTextSizeToggle = document.querySelector("#practiceTextSizeToggle");
const practiceTextSizeIcon = document.querySelector("#practiceTextSizeIcon");
const practiceTextSizeToggleText = document.querySelector("#practiceTextSizeToggleText");
const themeToggle = document.querySelector("#themeToggle");
const themeIcon = document.querySelector("#themeIcon");
const themeToggleText = document.querySelector("#themeToggleText");
const learningProgramOpen = document.querySelector("#learningProgramOpen");
const learningProgramOpenText = document.querySelector("#learningProgramOpenText");
const learningProgramDialog = document.querySelector("#learningProgramDialog");
const learningProgramTitle = document.querySelector("#learningProgramTitle");
const learningProgramClose = document.querySelector("#learningProgramClose");
const customPracticeDialog = document.querySelector("#customPracticeDialog");
const customPracticeTitle = document.querySelector("#customPracticeTitle");
const customPracticeClose = document.querySelector("#customPracticeClose");
const customPracticeTextLabel = document.querySelector("#customPracticeTextLabel");
const customPracticeText = document.querySelector("#customPracticeText");
const customPracticeLineCountLabel = document.querySelector("#customPracticeLineCountLabel");
const customPracticeLineCount = document.querySelector("#customPracticeLineCount");
const customPracticeRefresh = document.querySelector("#customPracticeRefresh");
const customPracticeStatus = document.querySelector("#customPracticeStatus");
const customPracticeCancel = document.querySelector("#customPracticeCancel");
const customPracticeStart = document.querySelector("#customPracticeStart");
const customKeyHighlightLabel = document.querySelector("#customKeyHighlightLabel");
const customKeyHighlightToggle = document.querySelector("#customKeyHighlightToggle");
const customKeyHighlightToggleText = document.querySelector("#customKeyHighlightToggleText");
const customFingerZonesLabel = document.querySelector("#customFingerZonesLabel");
const customFingerZonesToggle = document.querySelector("#customFingerZonesToggle");
const customFingerZonesToggleText = document.querySelector("#customFingerZonesToggleText");
const customFingerHighlightLabel = document.querySelector("#customFingerHighlightLabel");
const customFingerHighlightToggle = document.querySelector("#customFingerHighlightToggle");
const customFingerHighlightToggleText = document.querySelector("#customFingerHighlightToggleText");
const customPressHighlightLabel = document.querySelector("#customPressHighlightLabel");
const customPressHighlightToggle = document.querySelector("#customPressHighlightToggle");
const customPressHighlightToggleText = document.querySelector("#customPressHighlightToggleText");
const customShowFingersLabel = document.querySelector("#customShowFingersLabel");
const customShowFingersToggle = document.querySelector("#customShowFingersToggle");
const customShowFingersToggleText = document.querySelector("#customShowFingersToggleText");
const customAlternateLinesLabel = document.querySelector("#customAlternateLinesLabel");
const customAlternateLinesToggle = document.querySelector("#customAlternateLinesToggle");
const customAlternateLinesToggleText = document.querySelector("#customAlternateLinesToggleText");
const customMetronomeLabel = document.querySelector("#customMetronomeLabel");
const customMetronomeInput = document.querySelector("#customMetronomeInput");
const programCurrentProgressLabel = document.querySelector("#programCurrentProgressLabel");
const programCurrentProgress = document.querySelector("#programCurrentProgress");
const currentModuleProgressReset = document.querySelector("#currentModuleProgressReset");
const statsOpen = document.querySelector("#statsOpen");
const statsOpenText = document.querySelector("#statsOpenText");
const statsDialog = document.querySelector("#statsDialog");
const statsTitle = document.querySelector("#statsTitle");
const statsClose = document.querySelector("#statsClose");
const statsOverview = document.querySelector("#statsOverview");
const statsDailyLabel = document.querySelector("#statsDailyLabel");
const dailyStatsList = document.querySelector("#dailyStatsList");
const helpOpen = document.querySelector("#helpOpen");
const helpOpenText = document.querySelector("#helpOpenText");
const helpDialog = document.querySelector("#helpDialog");
const helpTitle = document.querySelector("#helpTitle");
const helpClose = document.querySelector("#helpClose");
const helpTextPractice = document.querySelector("#helpTextPractice");
const helpTextProgram = document.querySelector("#helpTextProgram");
const helpTextFingering = document.querySelector("#helpTextFingering");
const keyHighlightLabel = document.querySelector("#keyHighlightLabel");
const assistantsToggle = document.querySelector("#assistantsToggle");
const assistantsToggleText = document.querySelector("#assistantsToggleText");
const assistantsPanel = document.querySelector("#assistantsPanel");
const keyHighlightToggle = document.querySelector("#keyHighlightToggle");
const keyHighlightToggleText = document.querySelector("#keyHighlightToggleText");
const fingerZonesLabel = document.querySelector("#fingerZonesLabel");
const fingerZonesToggle = document.querySelector("#fingerZonesToggle");
const fingerZonesToggleText = document.querySelector("#fingerZonesToggleText");
const fingerHighlightLabel = document.querySelector("#fingerHighlightLabel");
const fingerHighlightToggle = document.querySelector("#fingerHighlightToggle");
const fingerHighlightToggleText = document.querySelector("#fingerHighlightToggleText");
const pressHighlightLabel = document.querySelector("#pressHighlightLabel");
const pressHighlightToggle = document.querySelector("#pressHighlightToggle");
const pressHighlightToggleText = document.querySelector("#pressHighlightToggleText");
const showFingersLabel = document.querySelector("#showFingersLabel");
const showFingersToggle = document.querySelector("#showFingersToggle");
const showFingersToggleText = document.querySelector("#showFingersToggleText");
const alternateLinesLabel = document.querySelector("#alternateLinesLabel");
const alternateLinesToggle = document.querySelector("#alternateLinesToggle");
const alternateLinesToggleText = document.querySelector("#alternateLinesToggleText");
const metronomeLabel = document.querySelector("#metronomeLabel");
const metronomeInput = document.querySelector("#metronomeInput");
const fingerMapOpen = document.querySelector("#fingerMapOpen");
const fingerMapSectionLabel = document.querySelector("#fingerMapSectionLabel");
const cloudSyncToggle = document.querySelector("#cloudSyncToggle");
const cloudSyncToggleText = document.querySelector("#cloudSyncToggleText");
const cloudSyncState = document.querySelector("#cloudSyncState");
const cloudSyncPanel = document.querySelector("#cloudSyncPanel");
const cloudAccountTitle = document.querySelector("#cloudAccountTitle");
const cloudAccountState = document.querySelector("#cloudAccountState");
const cloudAccountIntro = document.querySelector("#cloudAccountIntro");
const cloudAuthStart = document.querySelector("#cloudAuthStart");
const cloudAuthDivider = document.querySelector("#cloudAuthDivider");
const cloudLoginMode = document.querySelector("#cloudLoginMode");
const cloudCreateMode = document.querySelector("#cloudCreateMode");
const cloudCreateOptions = document.querySelector("#cloudCreateOptions");
const cloudCreateEmail = document.querySelector("#cloudCreateEmail");
const cloudCreateBack = document.querySelector("#cloudCreateBack");
const cloudCredentialFields = document.querySelector("#cloudCredentialFields");
const cloudEmailLabel = document.querySelector("#cloudEmailLabel");
const cloudEmailInput = document.querySelector("#cloudEmailInput");
const cloudPasswordLabel = document.querySelector("#cloudPasswordLabel");
const cloudPasswordInput = document.querySelector("#cloudPasswordInput");
const cloudProfileLabel = document.querySelector("#cloudProfileLabel");
const cloudProfileInput = document.querySelector("#cloudProfileInput");
const cloudOauthProviders = document.querySelector("#cloudOauthProviders");
const cloudActions = document.querySelector("#cloudActions");
const cloudLogin = document.querySelector("#cloudLogin");
const cloudRegister = document.querySelector("#cloudRegister");
const cloudImport = document.querySelector("#cloudImport");
const cloudLogout = document.querySelector("#cloudLogout");
const cloudDelete = document.querySelector("#cloudDelete");
const cloudLoginBack = document.querySelector("#cloudLoginBack");
const cloudStatus = document.querySelector("#cloudStatus");
const keyboardEditorPanel = document.querySelector("#keyboardEditorPanel");
const keyboardFingerPicker = document.querySelector("#keyboardFingerPicker");
const keyboardEditorReset = document.querySelector("#keyboardEditorReset");
const keyboardEditorCancel = document.querySelector("#keyboardEditorCancel");
const keyboardEditorSave = document.querySelector("#keyboardEditorSave");
const languageTabs = document.querySelector("#languageTabs");
const trainer = document.querySelector(".trainer");
const practiceProgress = document.querySelector(".practice-progress");
const practiceStats = document.querySelector(".practice-stats");
const practiceAccuracyLabel = document.querySelector("#practiceAccuracyLabel");
const practiceAccuracyValue = document.querySelector("#practiceAccuracyValue");
const practiceSpeedLabel = document.querySelector("#practiceSpeedLabel");
const practiceSpeedValue = document.querySelector("#practiceSpeedValue");
const practiceSample = document.querySelector("#practiceSample");
const practiceProgressText = document.querySelector("#practiceProgressText");
const practiceProgressBar = document.querySelector("#practiceProgressBar");
const practiceModuleCaption = document.querySelector("#practiceModuleCaption");
const practiceModuleList = document.querySelector("#practiceModuleList");
const keySelect = document.querySelector("#keySelect");
const labelInput = document.querySelector("#labelInput");
const applyLabel = document.querySelector("#applyLabel");
const editToggle = document.querySelector("#editToggle");
const resetLayout = document.querySelector("#resetLayout");
const status = document.querySelector("#status");

function refreshFingerNodes() {
  leftFingerNodes = Array.from(document.querySelectorAll('.hand.left .finger[data-finger]'));
  rightFingerNodes = Array.from(document.querySelectorAll('.hand.right .finger[data-finger]'));
}

async function hydrateFingerSvgs() {
  const fingerImages = Array.from(document.querySelectorAll('img.finger[data-finger]'));

  await Promise.all(fingerImages.map(async image => {
    try {
      const response = await fetch(image.getAttribute("src"));
      if (!response.ok) return;

      const svgMarkup = await response.text();
      const parsed = new DOMParser().parseFromString(svgMarkup, "image/svg+xml");
      const svg = parsed.documentElement;
      if (!svg || svg.nodeName.toLowerCase() !== "svg") return;

      svg.setAttribute("class", image.className);
      svg.setAttribute("data-finger", image.dataset.finger || "");
      svg.setAttribute("aria-hidden", "true");
      svg.querySelectorAll("[id]").forEach(node => node.removeAttribute("id"));
      image.replaceWith(svg);
    } catch {
      // Keep raster fallback if inline SVG hydration is unavailable.
    }
  }));

  refreshFingerNodes();
}
