window.PRACTICE_CONTENT_SOURCE.modules = window.PRACTICE_CONTENT_SOURCE.modules || [];
window.PRACTICE_CONTENT_SOURCE.modules.push({
  id: "module1",
  title: { ru: "Module 1 — Домашний ряд", de: "Modul 1 — Grundreihe", en: "Module 1 — Home Row" },
  lessons: [
    {
      id: "lesson1_1",
      title: { ru: "Левая рука (Ф Ы В А)", de: "Linke Hand (A S D F)", en: "Left Hand (A S D F)" },
      target: { lines: 10, accuracy: 90 },
      lines: {
        ru: [
          "фыва фыва фыва фыва вафы вафы авыф авыф фыва вафы авыф фыва вафы авыф авыф фыва фыва вафы авыф авыф фыва фыва вафы авыф авыф фыва фыва вафы авыф авыф фыва фыва вафы авыф авыф фыва фыва вафы авыф авыф фыва фыва вафы авыф авыф фыва фыва вафы авыф авыф фыва фыва вафы авыф авыф",
          "фф ыы вв аа фф вв ыы аа фф аа вв ыы фф ыы вв аа фф вв ыы аа фф аа вв ыы фф ыы вв аа фф вв ыы аа фф аа вв ыы фф ыы вв аа фф вв ыы аа фф аа вв ыы фф ыы вв аа фф вв ыы аа фф аа вв ыы фф ыы вв аа фф вв ыы аа фф аа вв ыы фф ыы вв аа фф вв ыы аа фф аа вв ыы фф ыы вв аа фф вв ыы аа фф аа вв ыы",
          "авав ывыв фафа вава авав ывыв фафа вава авав ывыв фафа вава авав ывыв фафа вава авав ывыв фафа вава авав ывыв фафа вава авав ывыв фафа вава авав ывыв фафа вава авав ывыв фафа вава авав ывыв фафа вава авав ывыв фафа вава авав ывыв фафа вава авав ывыв фафа вава",
          "афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф афф фыв ваф",
          "ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы ава афа авы",
          "ааа ффф ыыы ввв ааа ффф ыыы ввв ааа ффф ыыы ввв ааа ффф ыыы ввв ааа ффф ыыы ввв ааа ффф ыыы ввв ааа ффф ыыы ввв ааа ффф ыыы ввв ааа ффф ыыы ввв ааа ффф ыыы ввв ааа ффф ыыы ввв ааа ффф ыыы ввв ааа ффф ыыы ввв ааа ффф ыыы ввв ааа ффф ыыы ввв ааа ффф ыыы ввв ааа ффф ыыы ввв ааа ффф ыыы ввв",
          "вафф ывва аафф вафф ывва аафф вафф ывва аафф вафф ывва аафф вафф ывва аафф вафф ывва аафф вафф ывва аафф вафф ывва аафф вафф ывва аафф вафф ывва аафф вафф ывва аафф вафф ывва аафф вафф ывва аафф вафф ывва аафф вафф ывва аафф вафф ывва аафф вафф ывва аафф",
          "фффф аааа ыыыы вввв фффф аааа ыыыы вввв фффф аааа ыыыы вввв фффф аааа ыыыы вввв фффф аааа ыыыы вввв фффф аааа ыыыы вввв фффф аааа ыыыы вввв фффф аааа ыыыы вввв фффф аааа ыыыы вввв фффф аааа ыыыы вввв фффф аааа ыыыы вввв фффф аааа ыыыы вввв фффф аааа ыыыы вввв фффф аааа ыыыы вввв",
          "выв фаф авав выв фаф авав выв фаф авав выв фаф авав выв фаф авав выв фаф авав выв фаф авав выв фаф авав выв фаф авав выв фаф авав выв фаф авав выв фаф авав выв фаф авав выв фаф авав выв фаф авав выв фаф авав выв фаф авав выв фаф авав выв фаф авав выв фаф авав",
          "фывафывафыва вафывафывафы авыфавыфавыф фывафывафыва вафывафывафы авыфавыфавыф фывафывафыва вафывафывафы авыфавыфавыф фывафывафыва вафывафывафы авыфавыфавыф фывафывафыва вафывафывафы авыфавыфавыф фывафывафыва вафывафывафы авыфавыфавыф фывафывафыва вафывафывафы авыфавыфавыф"
        ],
        de: [
          "asdf asdf asdf asdf sadf sadf dsa fdsa asdf fdsa dsa fads asdf sad f ads fad sasd fds fads asdf fdsa sadf adsf fads asdf sadf dsa fdsa asdf fdsa dsa fads asdf sad f ads fad sasd fds fads asdf fdsa asdf sadf dsa fdsa asdf fdsa dsa fads asdf sad f ads fad sasd fds fads asdf fdsa sadf adsf fads",
          "ff ss aa dd ff dd ss aa ff ss dd aa dd ss ff aa dd ss aa ff dd ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd",
          "ads fads adf sad fads asdf asd fads asf ads fads asdf fad sadf asd fads asf ads fads asdf fad sadf asd fads asf ads fads asdf fad sadf asd fads asf ads fads adf sad fads asdf asd fads asf ads fads asdf fad sadf asd fads asf ads fads asdf fad sadf asd fads asf ads fads asdf fad sadf asd fads asf",
          "da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa",
          "fass dass lass fass dass lass fass dass lass fass dass lass fass dass lass fass dass lass fass dass lass fass dass lass fass dass lass fass dass lass fass dass lass fass dass lass fass dass lass fass dass lass fass dass lass fass dass lass fass dass lass fass dass lass fass dass lass fass dass lass",
          "asdf asdf asdf asdf sadf sadf dsa fdsa asdf fdsa dsa fads asdf sad f ads fad sasd fds fads asdf fdsa sadf adsf fads asdf sadf dsa fdsa asdf fdsa dsa fads asdf sad f ads fad sasd fds fads asdf fdsa asdf sadf dsa fdsa asdf fdsa dsa fads asdf sad f ads fad sasd fds fads asdf fdsa sadf adsf fads",
          "ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af",
          "sada fafa fass sasa fafa fass sada fafa fass sasa fafa fass sada fafa fass sasa fafa fass sada fafa fass sasa fafa fass sada fafa fass sasa fafa sada fafa fass sasa fafa fass sada fafa fass sasa fafa fass sada fafa fass sasa fafa fass sada fafa fass sasa fafa fass sada fafa fass sasa fafa",
          "asss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd",
          "asdfasdfasdfasdf sadfsadfsadfsadf fadsfadsfadsfads asdfasdfasdfasdf sadfsadfsadfsadf fadsfadsfadsfads asdfasdfasdfasdf sadfsadfsadfsadf fadsfadsfadsfads asdfasdfasdfasdf sadfsadfsadfsadf fadsfadsfadsfads asdfasdfasdfasdf sadfsadfsadfsadf fadsfadsfadsfads asdfasdfasdfasdf sadfsadfsadfsadf fadsfadsfadsfads"
        ],
        en: [
          "asdf asdf asdf asdf sadf sadf dsa fdsa asdf fdsa dsa fads asdf sad f ads fad sasd fds fads asdf fdsa sadf adsf fads asdf sadf dsa fdsa asdf fdsa dsa fads asdf sad f ads fad sasd fds fads asdf fdsa asdf sadf dsa fdsa asdf fdsa dsa fads asdf sad f ads fad sasd fds fads asdf fdsa sadf adsf fads",
          "ff ss aa dd ff dd ss aa ff ss dd aa dd ss ff aa dd ss aa ff dd ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd ff ss aa dd",
          "ads fads adf sad fads asdf asd fads asf ads fads asdf fad sadf asd fads asf ads fads asdf fad sadf asd fads asf ads fads asdf fad sadf asd fads asf ads fads adf sad fads asdf asd fads asf ads fads asdf fad sadf asd fads asf ads fads asdf fad sadf asd fads asf ads fads asdf fad sadf asd fads asf",
          "da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa da sa fa",
          "add ass sad fad dad add ass sad fad dad add ass sad fad dad add ass sad fad dad add ass sad fad dad add ass sad fad dad add ass sad fad dad add ass sad fad dad add ass sad fad dad add ass sad fad dad add ass sad fad dad add ass sad fad dad add ass sad fad dad add ass sad fad dad add ass sad fad dad",
          "fads asdf sadf dads fads asdf sadf dads fads asdf sadf dads fads asdf sadf dads fads asdf sadf dads fads asdf sadf dads fads asdf sadf dads fads asdf sadf dads fads asdf sadf dads fads asdf sadf dads fads asdf sadf dads fads asdf sadf dads fads asdf sadf dads fads asdf sadf dads fads asdf sadf dads",
          "ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af ds fa sd af",
          "sada fafa dads sasa fafa dads sada fafa dads sasa fafa dads sada fafa dads sasa fafa dads sada fafa dads sasa fafa dads sada fafa dads sasa fafa sada fafa dads sasa fafa dads sada fafa dads sasa fafa dads sada fafa dads sasa fafa dads sada fafa dads sasa fafa dads sada fafa dads sasa fafa",
          "asss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd ssss ffff aaaa dddd",
          "asdfasdfasdfasdf sadfsadfsadfsadf fadsfadsfadsfads asdfasdfasdfasdf sadfsadfsadfsadf fadsfadsfadsfads asdfasdfasdfasdf sadfsadfsadfsadf fadsfadsfadsfads asdfasdfasdfasdf sadfsadfsadfsadf fadsfadsfadsfads asdfasdfasdfasdf sadfsadfsadfsadf fadsfadsfadsfads asdfasdfasdfasdf sadfsadfsadfsadf fadsfadsfadsfads"
        ]
      }
    },
    {
      id: "lesson1_2",
      title: { ru: "Правая рука (О Л Д Ж)", de: "Rechte Hand (J K L Ö)", en: "Right Hand (J K L ;)" },
      target: { lines: 10, accuracy: 90 },
      lines: {
        ru: [
          "олдж олдж олдж олдж лдож лдож дло жлод олдж жлод дло олдж лдож дло олдж лдож дло жлод олдж олдж лдож дло олдж олдж лдож дло олдж олдж лдож дло олдж олдж лдож дло олдж олдж лдож дло олдж олдж лдож дло олдж олдж лдож дло олдж олдж лдож дло олдж олдж лдож дло олдж олдж лдож дло олдж олдж лдож дло",
          "оо лл дд жж оо жж дд лл оо лл дд жж оо жж дд лл оо лл дд жж оо жж дд лл оо лл дд жж оо жж дд лл оо лл дд жж оо жж дд лл оо лл дд жж оо жж дд лл оо лл дд жж оо жж дд лл оо лл дд жж оо жж дд лл оо лл дд жж оо жж дд лл оо лл дд жж оо жж дд лл оо лл дд жж оо жж дд лл",
          "ложа ложа дол ложа ложа дол ложа ложа дол ложа ложа дол ложа ложа дол ложа ложа дол ложа ложа дол ложа ложа дол ложа ложа дол ложа ложа дол ложа ложа дол ложа ложа дол ложа ложа дол ложа ложа дол ложа ложа дол ложа ложа дол ложа ложа дол ложа ложа дол ложа ложа дол ложа ложа дол",
          "олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло олдж ждло",
          "олл жоо доо лоо олл жоо доо лоо олл жоо доо лоо олл жоо доо лоо олл жоо доо лоо олл жоо доо лоо олл жоо доо лоо олл жоо доо лоо олл жоо доо лоо олл жоо доо лоо олл жоо доо лоо олл жоо доо лоо олл жоо доо лоо олл жоо доо лоо олл жоо доо лоо олл жоо доо лоо олл жоо доо лоо олл жоо доо лоо олл жоо доо лоо",
          "ооо ллл ддд жжж ооо ллл ддд жжж ооо ллл ддд жжж ооо ллл ддд жжж ооо ллл ддд жжж ооо ллл ддд жжж ооо ллл ддд жжж ооо ллл ддд жжж ооо ллл ддд жжж ооо ллл ддд жжж ооо ллл ддд жжж ооо ллл ддд жжж ооо ллл ддд жжж ооо ллл ддд жжж ооо ллл ддд жжж ооо ллл ддд жжж ооо ллл ддд жжж ооо ллл ддд жжж ооо ллл ддд жжж",
          "лдож дло олдж лдож дло олдж лдож дло олдж лдож дло олдж лдож дло олдж лдож дло олдж лдож дло олдж лдож дло олдж лдож дло олдж лдож дло олдж лдож дло олдж лдож дло олдж лдож дло олдж лдож дло олдж лдож дло олдж лдож дло олдж лдож дло олдж лдож дло олдж лдож дло олдж лдож дло олдж лдож дло олдж",
          "жооо дллл ооож жооо дллл ооож жооо дллл ооож жооо дллл ооож жооо дллл ооож жооо дллл ооож жооо дллл ооож жооо дллл ооож жооо дллл ооож жооо дллл ооож жооо дллл ооож жооо дллл ооож жооо дллл ооож жооо дллл ооож жооо дллл ооож жооо дллл ооож жооо дллл ооож жооо дллл ооож жооо дллл ооож жооо дллл ооож жооо дллл ооож",
          "оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол оллд жжол",
          "олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж олдж"
        ],
        de: [
          "jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj",
          "jj kk ll ;; jj ;; kk ll jj kk ;; ll jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ;; ll jj ;; kk ll",
          "all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay",
          "jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk",
          "ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj",
          "jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;;",
          "lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl",
          ";j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j;",
          "jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl;",
          "jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;;"
        ],
        en: [
          "jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj jkl; lk;j ;lkj",
          "jj kk ll ;; jj ;; kk ll jj kk ;; ll jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ;; ll jj ;; kk ll",
          "all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay all jak lay",
          "jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk jkl jlk ljk",
          "ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj ajl lja kaj laj",
          "jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;;",
          "lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl lkj ;lk jkl kjl",
          ";j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j; ;j ;k ;l l; k; j;",
          "jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl; jkl;jkl;jkl;",
          "jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;; jkl;;;;"
        ]
      }
    },
    {
      id: "lesson1_3",
      title: { ru: "Обе руки", de: "Beide Hände", en: "Both Hands" },
      target: { lines: 12, accuracy: 90 },
      lines: {
        ru: [
          "фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж",
          "ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж ф о ы л в д а ж",
          "ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж",
          "олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж",
          "вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод вафы жлод",
          "фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф фвао лджф",
          "выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа выфл джоа",
          "авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж",
          "ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а ф а в о л д ж а",
          "фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж",
          "фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж",
          "а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а ф ы в о л д ж а"
        ],
        de: [
          "asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl;",
          "f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k",
          "a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f",
          "jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf",
          "fass jkl; dass jkl; lass jkl; fass jkl; dass jkl; lass jkl; fass jkl; dass jkl; lass jkl; fass jkl; dass jkl; lass jkl; fass jkl; dass jkl; lass jkl; fass jkl; dass jkl; lass jkl; fass jkl; dass jkl; lass jkl; fass jkl; dass jkl; lass jkl; fass jkl; dass jkl; lass jkl; fass jkl; dass jkl; lass jkl; fass jkl; dass jkl; lass jkl;",
          "aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk",
          "dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass dfjk lass",
          "sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl",
          "a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f",
          "asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf",
          "asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdf asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdf",
          "jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj"
        ],
        en: [
          "asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl;",
          "f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k s l a ; f j d k",
          "a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f",
          "jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf",
          "fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl; fads jkl;",
          "aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk aslkd jflk",
          "dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals dfjk sals",
          "sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl sdk fjl",
          "a s d f g h j k l ; a s d f g h j k l ; a s d f g h j k l ; a s d f g h j k l ; a s d f g h j k l ; a s d f g h j k l ; a s d f g h j k l ; a s d f a s d f g h j k l ; a s d f g h j k l ; a s d f g h j k l ; a s d f g h j k l ; a s d f g h j k l ; a s d f g h j k l ; a s d f g h j k l ; a s d f",
          "asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf",
          "asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdf asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdf",
          "jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj jals kdfj"
        ]
      }
    },
    {
      id: "lesson1_4",
      title: { ru: "Короткие слова", de: "Kurze Wörter", en: "Short Words" },
      target: { lines: 10, accuracy: 92 },
      lines: {
        ru: [
          "вал зал лада вода фаза ложа жажда овал лава адов жала вал зал лада вода фаза ложа жажда овал лава адов жала вал зал лада вода фаза ложа жажда овал лава адов жала вал зал лада вода фаза ложа жажда овал лава адов жала вал зал лада вода фаза ложа жажда овал лава адов жала вал зал лада вода фаза",
          "фаза вода жажда вал зал лада ложа овал лава жала адов фаза вода жажда вал зал лада ложа овал лава жала адов фаза вода жажда вал зал лада ложа овал лава жала адов фаза вода жажда вал зал лада ложа овал лава жала адов фаза вода жажда вал зал лада ложа овал лава жала адов фаза вода жажда вал зал лада",
          "жажда лада овал зал вал вода ложа фаза лава адов жала жажда лада овал зал вал вода ложа фаза лава адов жала жажда лада овал зал вал вода ложа фаза лава адов жала жажда лада овал зал вал вода ложа фаза лава адов жала жажда лада овал зал вал вода ложа фаза лава адов жала жажда лада овал зал вал",
          "вода фаза ложа зал вал жажда овал лава адов жала лада вода фаза ложа зал вал жажда овал лава адов жала лада вода фаза ложа зал вал жажда овал лава адов жала лада вода фаза ложа зал вал жажда овал лава адов жала лада вода фаза ложа зал вал жажда овал лава адов жала лада вода фаза ложа зал вал жажда",
          "овал лава адов жала вал зал лада вода фаза ложа жажда овал лава адов жала вал зал лада вода фаза ложа жажда овал лава адов жала вал зал лада вода фаза ложа жажда овал лава адов жала вал зал лада вода фаза ложа жажда овал лава адов жала вал зал лада вода фаза ложа жажда овал лава адов жала вал зал",
          "лава жала вал зал лада вода фаза ложа жажда овал адов лава жала вал зал лада вода фаза ложа жажда овал адов лава жала вал зал лада вода фаза ложа жажда овал адов лава жала вал зал лада вода фаза ложа жажда овал адов лава жала вал зал лада вода фаза ложа жажда овал адов лава жала вал зал лада вода",
          "адов жажда ложа фаза вода лада зал вал овал лава жала адов жажда ложа фаза вода лада зал вал овал лава жала адов жажда ложа фаза вода лада зал вал овал лава жала адов жажда ложа фаза вода лада зал вал овал лава жала адов жажда ложа фаза вода лада зал вал овал лава жала адов жажда ложа фаза вода лада зал",
          "жала лава овал вал зал лада вода фаза ложа жажда адов жала лава овал вал зал лада вода фаза ложа жажда адов жала лава овал вал зал лада вода фаза ложа жажда адов жала лава овал вал зал лада вода фаза ложа жажда адов жала лава овал вал зал лада вода фаза ложа жажда адов жала лава овал вал зал лада вода",
          "ласса вода лада зал вал фаза ложа овал жажда лава жала ласса вода лада зал вал фаза ложа овал жажда лава жала ласса вода лада зал вал фаза ложа овал жажда лава жала ласса вода лада зал вал фаза ложа овал жажда лава жала ласса вода лада зал вал фаза ложа овал жажда лава жала ласса вода лада зал вал фаза ложа",
          "вал вал зал зал лада лада вода вода фаза фаза ложа ложа вал вал зал зал лада лада вода вода фаза фаза ложа ложа вал вал зал зал лада лада вода вода фаза фаза ложа ложа вал вал зал зал лада лада вода вода фаза фаза ложа ложа вал вал зал зал лада лада вода вода фаза фаза ложа ложа вал вал зал зал лада лада"
        ],
        de: [
          "als das falls lass fass sala dada alfa falk als das falls lass fass sala dada alfa falk als das falls lass fass sala dada alfa falk als das falls lass fass sala dada alfa falk als das falls lass fass sala dada alfa falk als das falls lass fass sala dada alfa falk als das falls lass fass sala dada alfa falk als das falls lass fass",
          "fass dass lass als falls sala dada alfa falk fass dass lass als falls sala dada alfa falk fass dass lass als falls sala dada alfa falk fass dass lass als falls sala dada alfa falk fass dass lass als falls sala dada alfa falk fass dass lass als falls sala dada alfa falk fass dass lass als falls sala dada alfa falk",
          "dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala",
          "falls lass fass sala als das dada falk falls lass fass sala als das dada falk falls lass fass sala als das dada falk falls lass fass sala als das dada falk falls lass fass sala als das dada falk falls lass fass sala als das dada falk falls lass fass sala als das dada falk falls lass fass sala als das dada falk falls",
          "lass sala dada falk als das falls fass lass sala dada falk als das falls fass lass sala dada falk als das falls fass lass sala dada falk als das falls fass lass sala dada falk als das falls fass lass sala dada falk als das falls fass lass sala dada falk als das falls fass lass sala dada falk als das falls fass lass",
          "sala dada falk falls lass fass als das sala dada falk falls lass fass als das sala dada falk falls lass fass als das sala dada falk falls lass fass als das sala dada falk falls lass fass als das sala dada falk falls lass fass als das sala dada falk falls lass fass als das sala dada falk falls lass fass als das sala dada",
          "falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk",
          "als falls lass fass sala dada falk das als falls lass fass sala dada falk das als falls lass fass sala dada falk das als falls lass fass sala dada falk das als falls lass fass sala dada falk das als falls lass fass sala dada falk das als falls lass fass sala dada falk das als falls lass fass sala dada falk das",
          "das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das",
          "falls lass fass als das sala dada falk falls lass fass als das sala dada falk falls lass fass als das sala dada falk falls lass fass als das sala dada falk falls lass fass als das sala dada falk falls lass fass als das sala dada falk falls lass fass als das sala dada falk falls lass fass als das sala dada falk falls"
        ],
        en: [
          "all sad dad ask fall lass flask lads flask all sad dad ask fall lass flask lads flask all sad dad ask fall lass flask lads flask all sad dad ask fall all sad dad ask fall lass flask lads flask all sad dad ask fall lass flask lads flask all sad dad ask fall lass flask lads flask all sad dad ask fall",
          "fads ask falls glass ask fall lass flask all sad dad ask fall lass flask lads flask all sad dad ask fall lass flask lads flask all sad dad fads ask falls glass ask fall lass flask all sad dad ask fall lass flask lads flask all sad dad ask fall lass flask lads flask all sad dad ask fall lass flask all sad dad",
          "sad all flask lads glass add lad sad all flask lads glass add lad sad all flask lads glass add lad sad all flask lads glass add lad sad all flask lads glass add lad sad all flask lads glass add lad sad all flask lads glass add lad sad all flask lads glass add lad sad all flask lads glass add lad",
          "ask fall lass flask lads glass add lad all sad dad ask fall lass flask lads glass add lad all sad dad ask fall lass flask lads glass add ask fall lass flask lads glass add lad all sad dad ask fall lass flask lads glass add lad all sad dad ask fall lass flask lads glass add lad all sad dad ask fall",
          "glass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add fall",
          "all fad ask all sad dad ask fall lass flask lads glass add lad all sad dad ask fall lass flask lads glass add lad all sad dad ask fall all fad ask all sad dad ask fall lass flask lads glass add lad all sad dad ask fall lass flask lads glass add lad all sad dad ask fall lass flask lads glass add lad",
          "add all glass ask sad lads fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask add all glass ask sad lads fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add fall",
          "lads fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lads fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add",
          "flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask all flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass",
          "fall glass ask fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add fall glass ask fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask"
        ]
      }
    },
    {
      id: "lesson1_5",
      title: { ru: "Тест", de: "Test", en: "Test" },
      target: { lines: 10, accuracy: 90, speed: 20 },
      lines: {
        ru: [
          "вал зал лада вода фаза ложа жажда овал лава адов жала вал зал лада вода фаза ложа жажда овал лава адов жала вал зал лада вода фаза ложа жажда овал лава адов жала вал зал лада вода фаза ложа жажда овал лава адов жала вал зал лада вода фаза ложа жажда овал лава адов жала вал зал лада вода фаза",
          "фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж фыва олдж",
          "лава жала адов жажда ложа фаза вода лада зал вал овал лава жала адов жажда ложа фаза вода лада зал вал овал лава жала адов жажда ложа фаза вода лада зал вал овал лава жала адов жажда ложа фаза вода лада зал вал овал лава жала адов жажда ложа фаза вода лада зал вал овал лава жала адов жажда ложа фаза",
          "ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж ф ы в а о л д ж",
          "авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж авдо лодж",
          "вал зал вода лада фаза ложа вал зал вода лада фаза ложа вал зал вода лада фаза ложа вал зал вода лада фаза ложа вал зал вода лада фаза ложа вал зал вода лада фаза ложа вал зал вода лада фаза ложа вал зал вода лада фаза ложа вал зал вода лада фаза ложа вал зал вода лада фаза ложа вал зал вода лада фаза ложа",
          "ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы ывфы авфы",
          "оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж оо лл дд жж",
          "а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в а д о в",
          "фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж фываолдж"
        ],
        de: [
          "als das falls lass fass sala dada alfa falk als das falls lass fass sala dada alfa falk als das falls lass fass sala dada alfa falk als das falls lass fass sala dada alfa falk als das falls lass fass sala dada alfa falk als das falls lass fass sala dada alfa falk als das falls lass fass sala dada alfa falk",
          "asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl;",
          "fass dass lass als falls sala dada alfa falk fass dass lass als falls sala dada alfa falk fass dass lass als falls sala dada alfa falk fass dass lass als falls sala dada alfa falk fass dass lass als falls sala dada alfa falk fass dass lass als falls sala dada alfa falk fass dass lass als falls sala dada alfa falk",
          "a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f",
          "dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala dada falk als das falls lass fass sala",
          "asdf sadf dsa fdsa asdf fdsa dsa fads asdf sad f ads fad sasd fds fads asdf fdsa sadf adsf fads asdf sadf dsa fdsa asdf fdsa dsa fads asdf asdf sadf dsa fdsa asdf fdsa dsa fads asdf sad f ads fad sasd fds fads asdf fdsa sadf adsf fads asdf sadf dsa fdsa asdf fdsa dsa fads asdf asdf sadf dsa fdsa",
          "jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; jj kk ll ;; jj ;; kk ll",
          "jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf",
          "als falls lass fass sala dada falk das als falls lass fass sala dada falk das als falls lass fass sala dada falk das als falls lass fass sala dada falk das als falls lass fass sala dada falk das als falls lass fass sala dada falk das als falls lass fass sala dada falk das als falls lass fass sala dada falk das",
          "asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdf asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdf asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl;"
        ],
        en: [
          "all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall all sad dad ask fall",
          "glass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask glass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask glass flask lads glass add fall lass",
          "ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall ask fall lass flask lads glass add fall",
          "sad all flask lads glass add lad all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add sad all flask lads glass add lad all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask lads glass add sad all flask lads glass add",
          "fads ask falls glass ask fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask lads fads ask falls glass ask fall lass flask all sad dad ask fall lass flask lads glass add fall lass flask all sad dad ask fall lass flask lads fads ask falls glass ask fall",
          "asdf sadf dsa fdsa asdf fdsa dsa fads asdf sad f ads fad sasd fds fads asdf fdsa sadf adsf fads asdf sadf dsa fdsa asdf fdsa dsa fads asdf asdf sadf dsa fdsa asdf fdsa dsa fads asdf sad f ads fad sasd fds fads asdf fdsa sadf adsf fads asdf sadf dsa fdsa asdf fdsa dsa fads asdf asdf sadf dsa fdsa",
          "jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; kk ll jj kk ll ;; jj ;; jj kk ll ;; jj ;; kk ll",
          "jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf",
          "a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f j k l ; a s d f",
          "asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdf asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdf asdfjkl;asdfjkl; asdfjkl;asdfjkl; asdfjkl;asdfjkl;"
        ]
      }
    }
  ]
});
